### ISSUE TITLE
运行demo代码报错，对python版本有要求吗

### ISSUE THREAD

**Issue by zeguangzhang** [APhun/moviepy-cn#4]
运行环境：python3.9， 安装moviepy成功
运行demo报错，第一句导入就报错。报错如下，是什么原因？
`Traceback (most recent call last):
  File "/Users/mac/project_python/pigqi/test/watermak.py", line 2, in <module>
    from moviepy.editor import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 173, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 33, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.`

**Comment by APhun** [comment]
> 运行环境：python3.9， 安装moviepy成功 运行demo报错，第一句导入就报错。报错如下，是什么原因？ `Traceback (most recent call last): File "/Users/mac/project_python/pigqi/test/watermak.py", line 2, in <module> from moviepy.editor import * File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/editor.py", line 36, in <module> from .video.io.VideoFileClip import VideoFileClip File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module> from moviepy.audio.io.AudioFileClip import AudioFileClip File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module> from moviepy.audio.AudioClip import AudioClip File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/audio/AudioClip.py", line 7, in <module> from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module> from moviepy.config import get_setting File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moviepy/config.py", line 36, in <module> FFMPEG_BINARY = get_exe() File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 173, in get_exe return imageio_ffmpeg.get_ffmpeg_exe() File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 33, in get_ffmpeg_exe raise RuntimeError( RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.`

是否正确安装和配置ffmpeg？
